### ISSUE TITLE
Request authenticating before permissions approval?

### ISSUE THREAD

**Issue by gwilakers** [alfw/passport-beam#1]
I guess this isn't really an issue as much as it is a question. Currently, the behavior I am seeing is this:
1. Not logged into Beam (aka no session data stored in the browser)
   - This works as expected. The user logs in, approves or denies requested permissions, and then is     redirected back to my application.
2. Logged into Beam (aka session data stored in the browser)
   - When logging into my application after having already logged into Beam previously, I am directed to the page where I would approve or deny requested permissions. The issue is that before I have any chance at all to actually approve or deny those permissions, I am redirected back to my application as authenticated since I have a previous Beam session stored.

My question is: Is there something I can pass to passport-beam to cause it to wait until I have actually approved or denied permissions here? Thanks!

**Comment by alfw** [comment]
Hello, sory for late response!

Beam recently added a flag to do this. When this was first made ther where no option for this. The last version i just pushed ( 1.0.4  ) has this turned on. I will make this a option later on, but i havent found a good way to handel it yet. So it's turned on by default!

**Comment by gwilakers** [comment]
Hey, no worries! Just downloaded that latest version and everything seems to be working as expected now. Thanks!
